apiVersion: v1
kind: Secret
metadata:
  name: studysync-secrets
  namespace: studysync-prod
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9rZWx2dG1vbmlfZGJfdXNlcjpkbjYzemhnS2oyTzVxSzB1QHN0dWR5c3luYy5sdmZzMGIzLm1vbmdvZGIubmV0L3N0dWR5c3luYz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
